import { Person } from "../models/person";

export const personsData : Person[] = [
 new Person(1, 'Rencista / emeryt', 'Pacjent', 'Optymalny', 'Optymalny', ' ', ' ', 'Nie', ' ', 'Nowoczesna diagnostyka', ' ', ' ', ' ', 'Nie', 'Dobrze', 'Kobieta', 'Bardzo dobrze', ' ', ' ', '2020/07/27 1:55:55 PM EET', 'Planowe przyjęcie do szpitala (zgodnie z wyznaczonym terminem hospitalizacji)', 'Przeciętnie', ' ', '30-49', 'Zawodowe', 'Dobrze', ''),
 new Person(2, 'Rencista / emeryt', 'Pacjent', 'Optymalny', 'Optymalny', ' ', ' ', 'Tak', ' ', 'Dobre opinie', ' ', ' ', ' ', 'Tak', 'Bardzo dobrze', 'Mężczyzna', 'Bardzo dobrze', 'Jest ok', ' ', '2020/07/27 6:20:38 PM EET', 'Planowe przyjęcie do szpitala (zgodnie z wyznaczonym terminem hospitalizacji)', 'Bardzo dobrze', ' ', 'powyżej 65 lat', 'Średnie', 'Bardzo dobrze', ' '),
 new Person(3, 'Rencista / emeryt', 'Pacjent', 'Optymalny', 'Długi', ' ', ' ', 'Tak', ' ', 'Dobre opinie;Sugestie rodziny/znajomych;Nowoczesna diagnostyka;Nowoczesne technologie medyczne;Wysoko wykwalifikowana kadra medyczna', ' ', ' ', ' ', 'Tak', 'Bardzo dobrze', 'Mężczyzna', 'Dobrze', ' ', ' ', '2020/08/01 2:20:19 PM EET', 'Planowe przyjęcie do szpitala (zgodnie z wyznaczonym terminem hospitalizacji)', 'Bardzo dobrze', ' ', 'powyżej 65 lat', 'Wyższe', 'Bardzo dobrze', ' '),
  new Person(4, 'Rencista / emeryt', 'Pacjent', 'Krótki', 'Krótki', ' ', ' ', 'Tak', ' ', 'Nie miałem/łam wpływu na wybór', ' ', ' ', ' ', 'Tak', 'Bardzo dobrze', 'Mężczyzna', 'Bardzo dobrze', ' ', ' ', '2020/08/03 2:15:57 PM EET', 'Planowe przyjęcie do szpitala (zgodnie z wyznaczonym terminem hospitalizacji)', 'Dobrze', ' ', 'powyżej 65 lat', 'Zawodowe', 'Bardzo dobrze', ' '),
  new Person(5, 'Rencista / emeryt', 'Pacjent', 'Optymalny', 'Krótki', ' ', ' ', 'Tak', ' ', 'Nie miałem/łam wpływu na wybór', ' ', ' ', ' ', 'Tak', 'Dobrze', 'Kobieta', 'Dobrze', ' ', ' ', '2020/08/03 2:20:32 PM EET', 'Planowe przyjęcie do szpitala (zgodnie z wyznaczonym terminem hospitalizacji)', 'Dobrze', ' ', 'powyżej 65 lat', 'Zawodowe', 'Dobrze', ' '),
  new Person(6, 'Rencista / emeryt', 'Pacjent', ' ', ' ', 'Optymalny', ' ', ' ', 'Bardzo dobrze', ' ', ' ', 'Dobrze', ' ', 'Tak', 'Dobrze', 'Kobieta', 'Dobrze', ' ', 'Nie', '2020/08/03 2:57:47 PM EET', 'Nagłe przyjęcie do szpitala (początkowo pomoc niesiona w szpitalnym oddziale ratunkowym/ izbie przyjęć)', 'Dobrze', 'Dobrze', 'powyżej 65 lat', 'Średnie', 'Dobrze', 'Przeciętna'),
  new Person(7, 'Rencista / emeryt', 'Pacjent', ' ', ' ', 'Optymalny', ' ', ' ', 'Przeciętnie', ' ', ' ', 'Przeciętnie', ' ', 'Tak', 'Przeciętnie', 'Mężczyzna', 'Przeciętnie', ' ', 'Tak', '2020/08/04 11:44:45 AM EET', 'Nagłe przyjęcie do szpitala (początkowo pomoc niesiona w szpitalnym oddziale ratunkowym/ izbie przyjęć)', 'Przeciętnie', 'Przeciętnie', 'powyżej 65 lat', 'Podstawowe', 'Przeciętnie', 'Przeciętna'),
  new Person(8, 'Rencista / emeryt', 'Pacjent', 'Długi', 'Długi', ' ', ' ', 'Tak', ' ', 'Nie miałem/łam wpływu na wybór', ' ', ' ', ' ', 'Tak', 'Bardzo dobrze', 'Mężczyzna', 'Bardzo dobrze', ' ', ' ', '2020/08/04 11:48:32 AM EET', 'Planowe przyjęcie do szpitala (zgodnie z wyznaczonym terminem hospitalizacji)', 'Dobrze', ' ', 'powyżej 65 lat', 'Zawodowe', 'Bardzo dobrze', ' '),
  new Person(9, 'Rencista / emeryt', 'Pacjent', ' ', ' ', 'Krótki', ' ', ' ', 'Bardzo dobrze', ' ', ' ', 'Bardzo dobrze', ' ', 'Tak', 'Dobrze', 'Mężczyzna', 'Bardzo dobrze', ' ', 'Tak', '2020/08/04 11:51:14 AM EET', 'Nagłe przyjęcie do szpitala (początkowo pomoc niesiona w szpitalnym oddziale ratunkowym/ izbie przyjęć)', 'Dobrze', 'Bardzo dobrze', 'powyżej 65 lat', 'Wyższe', 'Dobrze', 'Bardzo dobra'),
  new Person(10 , 'Rencista / emeryt', 'Pacjent', ' ', ' ', 'Krótki', ' ', ' ', 'Dobrze', ' ', ' ', 'Bardzo dobrze', ' ', 'Tak', 'Bardzo dobrze', 'Mężczyzna', 'Bardzo dobrze', ' ', 'Tak', '2020/08/04 11:55:08 AM EET', 'Nagłe przyjęcie do szpitala (początkowo pomoc niesiona w szpitalnym oddziale ratunkowym/ izbie przyjęć)', 'Dobrze', 'Dobrze', '50-65', 'Zawodowe', 'Bardzo dobrze', 'Dobra'),
  new Person(11 , 'Rencista / emeryt', 'Pacjent', 'Optymalny', 'Krótki', ' ', ' ', 'Tak', ' ', 'Sugestie rodziny/znajomych', ' ', ' ', ' ', 'Tak', 'Bardzo dobrze', 'Mężczyzna', 'Bardzo dobrze', ' ', ' ', '2020/08/05 12:09:02 PM EET', 'Planowe przyjęcie do szpitala (zgodnie z wyznaczonym terminem hospitalizacji)', 'Dobrze', ' ', 'powyżej 65 lat', 'Zawodowe', 'Bardzo dobrze', ' '),
  new Person(12 , 'Rencista / emeryt', 'Pacjent', 'Krótki', 'Krótki', ' ', ' ', 'Tak', ' ', 'Wysoko wykwalifikowana kadra medyczna', ' ', ' ', ' ', 'Tak', 'Bardzo dobrze', 'Kobieta', 'Bardzo dobrze', ' ', ' ', '2020/08/05 12:11:57 PM EET', 'Planowe przyjęcie do szpitala (zgodnie z wyznaczonym terminem hospitalizacji)', 'Bardzo dobrze', ' ', 'powyżej 65 lat', 'Średnie', 'Dobrze', ' '),
  new Person(13 , 'Rencista / emeryt', 'Pacjent', 'Optymalny', 'Optymalny', ' ', ' ', 'Tak', ' ', 'Nowoczesna diagnostyka;Nowoczesne technologie medyczne;Wysoko wykwalifikowana kadra medyczna', ' ', ' ', ' ', 'Tak', 'Przeciętnie', 'Mężczyzna', 'Przeciętnie', ' ', ' ', '2020/08/05 12:14:53 PM EET', 'Planowe przyjęcie do szpitala (zgodnie z wyznaczonym terminem hospitalizacji)', 'Przeciętnie', ' ', 'powyżej 65 lat', 'Zawodowe', 'Przeciętnie', ' '),
  new Person(14 , 'Osoba pracująca', 'Pacjent', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', 'Nie', 'Dobrze', 'Kobieta', 'Dobrze', ' ', ' ', '2020/08/06 10:08:45 AM EET', 'Leczenie kontynuowane po przeniesieniu z innej kliniki/oddziału', 'Bardzo dobrze', ' ', '30-49', 'Średnie', 'Bardzo dobrze', ' '),
  new Person(15, 'Osoba pracująca', 'Pacjent', 'Optymalny', 'Optymalny', ' ', ' ', 'Tak', ' ', 'Wysoko wykwalifikowana kadra medyczna;Nie miałem/łam wpływu na wybór', ' ', ' ', ' ', 'Tak', 'Bardzo dobrze', 'Kobieta', 'Bardzo dobrze', ' ', ' ', '2020/08/10 2:26:57 PM EET', 'Planowe przyjęcie do szpitala (zgodnie z wyznaczonym terminem hospitalizacji)', 'Bardzo dobrze', ' ', '30-49', 'Średnie', 'Bardzo dobrze', ' '),
  new Person(16, 'Rencista / emeryt', 'Pacjent', ' ', ' ', 'Optymalny', ' ', ' ', 'Dobrze', ' ', ' ', 'Dobrze', ' ', 'Tak', 'Dobrze', 'Mężczyzna', 'Dobrze', ' ', 'Tak', '2020/08/10 3:30:29 PM EET', 'Nagłe przyjęcie do szpitala (początkowo pomoc niesiona w szpitalnym oddziale ratunkowym/ izbie przyjęć)', 'Dobrze', 'Dobrze', 'powyżej 65 lat', 'Zawodowe', 'Dobrze', 'Przeciętna'),
  new Person(18, 'Osoba pracująca', 'Pacjent', ' ', ' ', 'Optymalny', ' ', ' ', 'Dobrze', ' ', ' ', 'Dobrze', ' ', 'Tak', 'Przeciętnie', 'Mężczyzna', 'Dobrze', ' ', 'Tak', '2020/08/10 3:42:37 PM EET', 'Nagłe przyjęcie do szpitala (początkowo pomoc niesiona w szpitalnym oddziale ratunkowym/ izbie przyjęć)', 'Przeciętnie', 'Dobrze', '50-65', 'Zawodowe', 'Dobrze', 'Dobra'),
  new Person(19, 'Rencista / emeryt', 'Pacjent', ' ', ' ', 'Optymalny', ' ', ' ', 'Bardzo dobrze', ' ', ' ', 'Bardzo dobrze', ' ', 'Tak', 'Bardzo dobrze', 'Mężczyzna', 'Bardzo dobrze', ' ', 'Tak', '2020/08/11 11:46:48 AM EET', 'Nagłe przyjęcie do szpitala (początkowo pomoc niesiona w szpitalnym oddziale ratunkowym/ izbie przyjęć)', 'Bardzo dobrze', 'Bardzo dobrze', 'powyżej 65 lat', 'Podstawowe', 'Bardzo dobrze', 'Bardzo dobra'),
  new Person(20, 'Rencista / emeryt', 'Pacjent', 'Optymalny', 'Długi', ' ', ' ', 'Tak', ' ', 'Nie miałem/łam wpływu na wybór', 'Częstsze wizyty lekarskie w czasie pobytu', ' ', ' ', 'Tak', 'Przeciętnie', 'Kobieta', 'Dobrze', 'Nie mam', ' ', '2020/08/11 12:02:59 PM EET', 'Planowe przyjęcie do szpitala (zgodnie z wyznaczonym terminem hospitalizacji)', 'Dobrze', ' ', 'powyżej 65 lat', 'Średnie', 'Dobrze', ' ')
  

  
]
